#!/usr/bin/env python3
"""
B.2 Post-processing — Normalization Level Breakdown from re-evaluation.

Reads predictions.csv files that include raw_text and normalization_level columns
(generated by eval.py --log_raw_text). Generates the level breakdown table and
diffs predictions against originals to verify reproducibility.

Output: audits/round2/B2_normalization_level_breakdown.md
"""

import os
import sys
from pathlib import Path
from collections import Counter

import pandas as pd

ROOT = Path("/mnt/fast/nobackup/users/gb0048/opro3_final")
sys.path.insert(0, str(ROOT))

CONSOLIDATED = ROOT / "results" / "BEST_CONSOLIDATED"
AUDITS_DIR = ROOT / "audits" / "round2"
B2_DIR = AUDITS_DIR / "b2_normalization"

CONFIGS_RERUN = {
    "02_base_opro_llm": {
        "display": "Base+OPRO-LLM",
        "original": CONSOLIDATED / "02_qwen2_base_opro_llm" / "evaluation" / "predictions.csv",
        "rerun": B2_DIR / "02_base_opro_llm" / "predictions.csv",
    },
    "06_lora_opro_template": {
        "display": "LoRA+OPRO-Tmpl",
        "original": CONSOLIDATED / "06_qwen2_lora_opro_template" / "evaluation" / "predictions.csv",
        "rerun": B2_DIR / "06_lora_opro_template" / "predictions.csv",
    },
    "07_qwen3_baseline": {
        "display": "Qwen3+Hand",
        "original": CONSOLIDATED / "07_qwen3_omni_baseline" / "evaluation" / "predictions.csv",
        "rerun": B2_DIR / "07_qwen3_baseline" / "predictions.csv",
    },
}

LEVEL_ORDER = [
    "L1_NONSPEECH",
    "L2_SPEECH",
    "L3_LETTER",
    "L4_YESNO",
    "L5_KEYWORDS",
    "L6_LLM_FALLBACK",
    "L6_UNKNOWN",
    "ERROR",
]

LEVEL_NAMES = {
    "L1_NONSPEECH": "L1: NONSPEECH substring",
    "L2_SPEECH": "L2: SPEECH substring",
    "L3_LETTER": "L3: Letter mapping (A/B)",
    "L4_YESNO": "L4: YES/NO response",
    "L5_KEYWORDS": "L5: Semantic keywords",
    "L6_LLM_FALLBACK": "L6a: LLM fallback (resolved)",
    "L6_UNKNOWN": "L6b: Unknown/unparseable",
    "ERROR": "Error (inference failure)",
}


def diff_predictions(original_path: str, rerun_path: str) -> dict:
    """Compare prediction columns between original and re-run."""
    df_orig = pd.read_csv(original_path)
    df_rerun = pd.read_csv(rerun_path)

    # Normalize predictions for comparison
    def canon(s):
        s = str(s).strip().upper()
        return s.replace("NON-SPEECH", "NONSPEECH").replace("NON SPEECH", "NONSPEECH")

    df_orig["pred_canon"] = df_orig["prediction"].apply(canon)
    df_rerun["pred_canon"] = df_rerun["prediction"].apply(canon)

    n_total = len(df_orig)
    n_match = (df_orig["pred_canon"] == df_rerun["pred_canon"]).sum()
    n_diff = n_total - n_match

    mismatches = []
    if n_diff > 0:
        mask = df_orig["pred_canon"] != df_rerun["pred_canon"]
        for idx in df_orig[mask].index[:10]:  # Show first 10 mismatches
            mismatches.append({
                "index": int(idx),
                "audio": os.path.basename(df_orig.loc[idx, "audio_path"]),
                "original": df_orig.loc[idx, "pred_canon"],
                "rerun": df_rerun.loc[idx, "pred_canon"],
            })

    return {
        "n_total": n_total,
        "n_match": n_match,
        "n_diff": n_diff,
        "match_rate": n_match / n_total * 100 if n_total > 0 else 0,
        "mismatches": mismatches,
    }


def analyze_level_breakdown(rerun_path: str) -> dict:
    """Analyze normalization level distribution."""
    df = pd.read_csv(rerun_path)

    if "normalization_level" not in df.columns:
        return {"error": "normalization_level column not found"}

    level_counts = Counter(df["normalization_level"].fillna("L6_UNKNOWN"))
    total = len(df)

    return {
        "total": total,
        "counts": dict(level_counts),
        "pcts": {k: v / total * 100 for k, v in level_counts.items()},
    }


def analyze_unknown_raw_text(rerun_path: str) -> list:
    """Inspect raw text of UNKNOWN/unparseable responses."""
    df = pd.read_csv(rerun_path)

    unknown_mask = df["normalization_level"].isin(["L6_UNKNOWN", "L6_LLM_FALLBACK", "ERROR"])
    df_unknown = df[unknown_mask]

    if len(df_unknown) == 0:
        return []

    samples = []
    for _, row in df_unknown.head(20).iterrows():
        samples.append({
            "audio": os.path.basename(str(row.get("audio_path", ""))),
            "raw_text": str(row.get("raw_text", ""))[:200],
            "level": row.get("normalization_level", ""),
            "prediction": row.get("prediction", ""),
        })

    return samples


def main():
    print("=" * 60)
    print("B.2 — Normalization Level Breakdown Analysis")
    print("=" * 60)

    lines = []
    lines.append("# B.2 — Normalization Level Breakdown (Test Set)")
    lines.append(f"**Date:** 2026-02-17")
    lines.append("")

    any_found = False

    for config_id, config in CONFIGS_RERUN.items():
        rerun_path = config["rerun"]
        original_path = config["original"]
        display = config["display"]

        if not rerun_path.exists():
            print(f"  SKIP: {display} — re-run predictions not found at {rerun_path}")
            continue

        any_found = True
        print(f"\nAnalyzing {display}...")

        # 1. Diff against original
        print("  Diffing against original predictions...")
        diff = diff_predictions(str(original_path), str(rerun_path))
        print(f"  Match rate: {diff['match_rate']:.2f}% ({diff['n_match']}/{diff['n_total']})")

        # 2. Level breakdown
        print("  Computing level breakdown...")
        breakdown = analyze_level_breakdown(str(rerun_path))

        # 3. Inspect unknowns
        unknowns = analyze_unknown_raw_text(str(rerun_path))

        # Generate report section
        lines.append(f"## {display}")
        lines.append("")

        # Reproducibility
        lines.append(f"### Reproducibility Check")
        lines.append(f"- Predictions matched original: **{diff['match_rate']:.2f}%** "
                     f"({diff['n_match']}/{diff['n_total']})")
        if diff["n_diff"] > 0:
            lines.append(f"- **{diff['n_diff']} mismatches detected** (see below)")
            lines.append("")
            lines.append("| Index | Audio | Original | Rerun |")
            lines.append("|-------|-------|----------|-------|")
            for mm in diff["mismatches"]:
                lines.append(f"| {mm['index']} | {mm['audio']} | {mm['original']} | {mm['rerun']} |")
        else:
            lines.append(f"- **Perfect match** — greedy decoding is deterministic")
        lines.append("")

        # Level breakdown table
        if "error" not in breakdown:
            lines.append(f"### Normalization Level Breakdown (n={breakdown['total']:,})")
            lines.append("")
            lines.append("| Level | Count | Percentage |")
            lines.append("|-------|-------|------------|")

            for level in LEVEL_ORDER:
                count = breakdown["counts"].get(level, 0)
                pct = breakdown["pcts"].get(level, 0.0)
                name = LEVEL_NAMES.get(level, level)
                if count > 0:
                    lines.append(f"| {name} | {count:,} | {pct:.2f}% |")

            # L1+L2 combined
            l1 = breakdown["counts"].get("L1_NONSPEECH", 0)
            l2 = breakdown["counts"].get("L2_SPEECH", 0)
            l1l2_pct = (l1 + l2) / breakdown["total"] * 100 if breakdown["total"] > 0 else 0
            lines.append(f"| **L1+L2 combined** | **{l1+l2:,}** | **{l1l2_pct:.2f}%** |")
            lines.append("")

        # Unknown responses analysis
        if unknowns:
            lines.append(f"### Unparseable/Fallback Responses (first {len(unknowns)})")
            lines.append("")
            lines.append("| Audio | Level | Prediction | Raw Text (truncated) |")
            lines.append("|-------|-------|------------|---------------------|")
            for u in unknowns:
                raw = u["raw_text"].replace("|", "\\|").replace("\n", " ")[:100]
                lines.append(f"| {u['audio']} | {u['level']} | {u['prediction']} | {raw} |")
            lines.append("")

    if not any_found:
        lines.append("**No re-run predictions found.** Run the B.2 SLURM job first.")
        lines.append("")
        lines.append("Expected paths:")
        for config_id, config in CONFIGS_RERUN.items():
            lines.append(f"- {config['rerun']}")

    report = "\n".join(lines)
    output_path = AUDITS_DIR / "B2_normalization_level_breakdown.md"
    output_path.write_text(report)
    print(f"\nReport saved to: {output_path}")


if __name__ == "__main__":
    main()
